export { TidyNode, createTree, getNodes, getEdges, getBoundingBox } from "./node.ts";
export type { InputNode, LayoutOptions, NodeInfo, Edge, BoundingBox } from "./types.ts";
export { relayout } from "./algorithm/partial-relayout.ts";
export { nonLayeredTidyTree } from "./algorithm/non-layered-tidy.ts";
import { rightLogical } from "./layouts/right-logical.ts";
import { leftLogical } from "./layouts/left-logical.ts";
import { downward } from "./layouts/downward.ts";
import { upward } from "./layouts/upward.ts";
import { standard } from "./layouts/standard.ts";
export const layout = { rightLogical, leftLogical, downward, upward, standard };
export { rightLogical, leftLogical, downward, upward, standard };
